config/routes.rb
Rails.application.routes.draw do
  get 'books/search'
  get 'books/new_search'
  resources :books

  get 'home/index'
  get 'users/first'
  resources :users

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root 'home#index'

end

app/models/book.rb
class Book < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

 def self.find_for_oauth(auth)
    user = User.where(uid: auth.uid, provider: auth.provider).first

    unless user
      user = User.create(
        uid:      auth.uid,
        provider: auth.provider,
        email:    User.dummy_email(auth),
        password: Devise.friendly_token[0, 20]
      )
    end

    user
  end

  private

  def self.dummy_email(auth)
    "#{auth.uid}-#{auth.provider}@example.com"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to action: 'index', notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search
    @books = []
    return if params['keywords'].blank?

    items = Amazon::Ecs.item_search(params['keywords'],
                                   search_index:   'Books',
                                   response_group: 'Medium',
                                   country:        'jp'
                                   ).items
    items.each do |item|
      element = item.get_element('ItemAttributes')
      @books << Book.new(
        asin: item.get('ASIN'),
        title: element.get('Title'),
        isbn: element.get('ISBN'),
        author: element.get_array('Author').join(', '),
        product_group: element.get('ProductGroup'),
        manufacturer: element.get('Manufacturer'),
        publication_date: element.get('PublicationDate'),
        small_image: item.get('SmallImage/URL'),
        medium_image: item.get('MediumImage/URL'),
        large_image: item.get('LargeImage/URL')
      )
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(
        :asin, :title, :isbn, :author, :product_group, :manufacturer,
        :publication_date, :small_image, :medium_image, :large_image)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @user = User.first
    @books = Book.all.order('updated_at DESC')
    @comments = [
      '実践的なノウハウが多くすばらしい本です。
      最初の数頁で、データ分析の難しさと本の意義がわかります。
      同じような状況にはなりにくいテーマですが
      応用性はあり、とても良い本です。',
      'Pythonのサンプルコードが多く、演習書としては充実しています。
      だたし、機械学習の各手法については、この本では理解できないと思います。他の教科書で基本を学んだあとにこれで演習すると良い結果を有むのではないでしょうか',
      '人口知能の進捗状況について、その実践例として、この本からくみ取ることができた。',
      '機械学習について、そこまで深く記載されているわけではないですが、動くコードとともに進められるので、イメージがつきやすいと思います。
      いろいろな分野が混ざっているので、本書を読んでから、興味のある分野を深堀りするのがいいと思います。'
    ]
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    callback_from :facebook
  end

  private

  def callback_from(provider)

    provider = provider.to_s
    @user = User.find_for_oauth(request.env['omniauth.auth'])

    if @user.persisted?
      flash[:notice] = I18n.t('devise.omniauth_callbacks.success', kind: provider.capitalize)
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.#{provider}_data"] = request.env['omniauth.auth']
      redirect_to users_first
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to :controller => 'home', action: 'index', notice: 'User was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /users/1
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
    end
  end

  # GET /users/first
  def first
    if user_signed_in?
      @user = current_user
      @user.email = ''
    else
      @user = User.new(
        id: 1,
        email: '',
        uid: '851939321543634',
        provider: 'facebook'
      )
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(
        :name, :email, :password, :password_confirmation,
        :reset_password_sent_at, :remember_created_at, :sign_in_count,
        :current_sign_in_at, :last_sign_in_at, :current_sign_in_ip,
        :last_sign_in_ip, :uid, :provider
      )
    end
end

app/helpers/amazon_helper.rb
module AmazonHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<%= form_for(@book, :html => { class: 'pure-form pure-form-aligned' })  do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :asin %><br>
    <%= f.text_field :asin %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :isbn %><br>
    <%= f.text_field :isbn %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :product_group %><br>
    <%= f.text_field :product_group %>
  </div>
  <div class="field">
    <%= f.label :manufacturer %><br>
    <%= f.text_field :manufacturer %>
  </div>
  <div class="field">
    <%= f.label :publication_date %><br>
    <%= f.date_select :publication_date %>
  </div>
  <div class="field">
    <%= f.label :small_image %><br>
    <%= f.text_field :small_image %>
  </div>
  <div class="field">
    <%= f.label :medium_image %><br>
    <%= f.text_field :medium_image %>
  </div>
  <div class="field">
    <%= f.label :large_image %><br>
    <%= f.text_field :large_image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Books</h1>

<table class='pure-table pure-table-bordered'>
  <thead>
    <tr>
      <th>image</th>
      <th>Title</th>
      <th>Author</th>
      <th>Product group</th>
      <th>Manufacturer</th>
      <th>Publication date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><img src="<%= book.small_image %>" /></td>
        <td><%= book.title %></td>
        <td><%= book.author %></td>
        <td><%= book.product_group %></td>
        <td><%= book.manufacturer %></td>
        <td><%= book.publication_date %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', books_search_path, class: 'pure-button' %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/search.html.erb
<%= form_tag books_search_path, style: 'pure-form', method: 'get' do %>
  <p>
    <%= text_field_tag :keywords, params[:keywords] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>

<table class='pure-table pure-table-bordered'>
  <thead>
    <tr>
      <th>Image</th>
      <th>Title</th>
      <th>Author</th>
      <th>Product group</th>
      <th>Manufacturer</th>
      <th>Publication date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><img src="<%= book.small_image %>" /></td>
        <td><%= book.title %></td>
        <td><%= book.author %></td>
        <td><%= book.product_group %></td>
        <td><%= book.manufacturer %></td>
        <td><%= book.publication_date %></td>
        <td>
          <%= form_for(book) do |f| %>
            <div style='display: none'>
              <%= f.text_field :asin %>
              <%= f.text_field :title %>
              <%= f.text_field :isbn %>
              <%= f.text_field :author %>
              <%= f.text_field :product_group %>
              <%= f.text_field :manufacturer %>
              <%= f.date_select :publication_date %>
              <%= f.text_field :small_image %>
              <%= f.text_field :medium_image %>
              <%= f.text_field :large_image %>
            </div>
            <div class="actions">
              <%= f.submit %>
            </div>
          <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<% @book = @books.first %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Asin:</strong>
  <%= @book.asin %>
</p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Isbn:</strong>
  <%= @book.isbn %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<p>
  <strong>Product group:</strong>
  <%= @book.product_group %>
</p>

<p>
  <strong>Manufacturer:</strong>
  <%= @book.manufacturer %>
</p>

<p>
  <strong>Publication date:</strong>
  <%= @book.publication_date %>
</p>

<p>
  <strong>Small image:</strong>
  <%= @book.small_image %>
</p>

<p>
  <strong>Medium image:</strong>
  <%= @book.medium_image %>
</p>

<p>
  <strong>Large image:</strong>
  <%= @book.large_image %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/home/index.html.erb
<h1>Time Line</h1>

<table class='pure-table'>

  <% @books.each_with_index do |book, i| %>
    <% if (i % 2 == 0) then%><tr><% end %>

      <% style_class = i.odd? ? 'left_line' : 'right_line' %>
      <th class=<%= style_class %> >
        <div>
          <div class='pure-u-1'>
            <img src='<%= book.large_image %>' />
          </div>
          <div class='pure-g'>
            <div class='pure-u-1-6'>
              <img src='https://graph.facebook.com/<%= @user.uid %>/picture'>
            </div>
            <div class='pure-u-5-6'>
              <p><%= @comments.shuffle.first %></p>
            </div>
          </div>
        </div>
      </th>
  <% end %>
</table>

app/views/layouts/_menu.html.erb
<div id="nav" class="pure-u">

  <div class="nav-inner">
    <a href="/"><button class="primary-button pure-button">Readist</button></a>

    <div class="pure-menu">
      <ul class="pure-menu-list">
        <li class="pure-menu-item">
          <% if user_signed_in? %>
            <%= current_user.name %>
            [<%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: "pure-menu-link" %>]
          <% else %>
              <%= link_to "Facebookでログイン", user_omniauth_authorize_path(:facebook), class: "pure-menu-link" %>
          <% end %>
        </li>
        <li class="pure-menu-item"><a href="/books/search" class="pure-menu-link">お気に入りを追加</a></li>
        <li class="pure-menu-item"><a href="#" class="pure-menu-link">おすすめ<span>(2)</span></a></li>
        <li class="pure-menu-item"><a href="#" class="pure-menu-link">フォロー</a></li>
        <li class="pure-menu-item"><a href="#" class="pure-menu-link">ビジネス</a></li>
        <li class="pure-menu-item"><a href="#" class="pure-menu-link">コミック</a></li>
        <li class="pure-menu-item"><a href="#" class="pure-menu-link">小説</a></li>
        <li class="pure-menu-item"><a href="#" class="pure-menu-link">雑誌</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Readist</title>
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>
  <body>

    <div class='content pure-g'>

      <div class='pure-u-1-6'>
        <%= render 'layouts/menu' %>
      </div>

      <div class='pure-u-5-6'>
        <%= yield %>
      </div>
    </div>

  </body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user, :html => { class: 'pure-form pure-form-aligned' }) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, '表示名' %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email, 'メールアドレス' %><br>
    <%= f.email_field :email %>
  </div>

  <div class="field">
    <%= f.label :password, 'パスワード' %><br>
    <%= f.password_field :password %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation, 'パスワード(確認用)' %><br>
    <%= f.password_field :password_confirmation %>
  </div>

  <div style='display:none'>
    <%= f.text_field :uid %>
    <%= f.text_field :provider %>
  </div>

  <div class="actions">
    <%= f.submit :class => 'pure-button pure-button-primary' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/first.html.erb
<h1>ユーザ登録を完了してください</h1>

<% if @user.uid %>
  <img src='https://graph.facebook.com/<%= @user.uid %>/picture'>
<% end %>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>